<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>OAML.Security</RootNamespace>
        <AssemblyName>OAML.Security</AssemblyName>
        <Deterministic>true</Deterministic>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BouncyCastle" Version="1.8.9" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\OAML\OAML.csproj" />
    </ItemGroup>

</Project>