<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\OAML.Domain\OAML.Domain.csproj" />
      <ProjectReference Include="..\OAML.Infrastructure\OAML.Infrastructure.csproj" />
      <ProjectReference Include="..\OAML.Protocol\OAML.Protocol.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="settings.json" />
      <Content Include="settings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
    </ItemGroup>

</Project>
